version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web_invexqr
    ports:
      - "8086:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: invexqr
      DB_USER: invexqr_user
      DB_PASSWORD: invexqr2025

  db:
    image: postgres:15
    container_name: postgres_invexqr_db
    restart: always
    environment:
      POSTGRES_DB: invexqr
      POSTGRES_USER: invexqr_user
      POSTGRES_PASSWORD: invexqr2025
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
