
services:
  web:
    image: php:8.2-apache
    container_name: php_web
    ports:
      - "8087:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: invexqr
      DB_USER: postgres
      DB_PASSWORD: invexqr2025

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: invexqr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: invexqr2025
      VITE_FIREBASE_API_KEY: AIzaSyAEdlkepge2d3SnlLrpEoJkqv8PAjISfVA
      VITE_FIREBASE_APP_ID: invextrack-a1001
      VITE_FIREBASE_PROJECT_ID: 1:746716963518:web:0faf49c4b09299ba2a74ef
      SESSION_SECRET: I$yXqM7ZfR3!Tq1cWopE8Azz0m2YBkPv
      PAYPAL_CLIENT_ID: AXu-EpJWDQ7Bl7Z_rQ6llW8QokphIfWfBPeyfv1aHbqQl8wGS5Ak_l6P0YCJtp3r2BYlQn6-zP_MjG7v
      PAYPAL_CLIENT_SECRET: sk_9a8s7df98a7sdf98a7sd9f8a7sd9f87a
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

